language: cpp
compiler:
  - gcc
before_install:
  - echo $LANG
  - echo $LC_ALL
before_script:
  - travis_retry bundle
  - travis_retry ./configure
branches:
  only:
    - master
notifications:
  recipients:
    - justin@micropenguin.net
  email:
    on_success: change
    on_failure: always

    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
env:
  - RVM=2.0.0 LANG="en_US.UTF-8"
os:
  - linux
  - osx
