######################################################################
# Automatically generated by qmake (3.0) Mon Jun 2 10:13:33 2014
######################################################################


QT += widgets
QT += concurrent
CONFIG += c++11

TEMPLATE = app
TARGET = PenguSniff
INCLUDEPATH += . Headers

# Input
HEADERS += Headers/getfiletotal.h Headers/mainwindow.h Headers/worker.h
FORMS += mainwindow.ui
SOURCES += Sources/main.cpp Sources/mainwindow.cpp
