######################################################################
# Automatically generated by qmake (3.0) Tue May 27 00:52:39 2014
######################################################################

QT += widgets
QT += concurrent
CONFIG += c++11

TEMPLATE = app
TARGET = PenguSniff
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h worker.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp

